on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cprecioso/action-prepare-node@v1
      - run: yarn pack -o package.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: package.tgz
          path: package.tgz
          if-no-files-found: error
