on:
  workflow_dispatch:
  workflow_call:

name: Publish

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    environment:
      name: npm-latest
      url: https://www.npmjs.com/package/tiss

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/

      - uses: actions/download-artifact@v4
        with:
          name: package.tgz

      - run: npm install -g npm
      - run: npm publish --provenance --access public package.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  publish-docs:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
